/* [HEED MY WARNING FELLOW DEV!] This file was auto-generated during build by '/pre-build/projects.js'. Any changes to this file directly will not persist after building. [FARE THEE WELL] */

// Type Imports:
import type { Chain } from './types';

// Projects List:
export const projects: Record<Chain, string[]> = {
	arb: [
		'aave_v3',
		'beefy',
		'cream',
	],
	avax: [
		'aave_v2',
		'aave_v3',
		'alligator',
		'autofarm',
		'avalaunch',
		'axial',
		'beefy',
		'benqi',
		'curve',
		'lostworlds',
		'pangolin',
		'penguin',
		'platypus',
		'pooltogether_v4',
		'snowball',
		'teddy',
		'traderjoe_v2',
		'traderjoe_v3',
		'yieldyak',
	],
	bsc: [
		'apeswap',
		'autofarm',
		'beefy',
		'belt',
		'cream',
		'moonpot',
		'pancakeswap_v1',
		'pancakeswap_v2',
		'venus',
	],
	cronos: [
		'autofarm',
		'beefy',
	],
	eth: [
		'aave_v2',
		'apwine',
		'balancer',
		'beefy',
		'compound',
		'cream',
		'curve',
		'mstable',
		'pooltogether_v4',
		'sushiswap_v1',
		'sushiswap_v2',
		'yearn',
	],
	ftm: [
		'aave_v3',
		'autofarm',
		'beefy',
		'beethovenx',
		'bouje',
		'cream',
		'curve',
		'scream',
		'spookyswap',
	],
	op: [
		'aave_v3',
		'beefy',
		'pika',
		'pooltogether_v4',
	],
	poly: [
		'aave_v2',
		'aave_v3',
		'apeswap',
		'apwine',
		'autofarm',
		'balancer',
		'beefy',
		'cream',
		'curve',
		'mstable',
		'pooltogether_v4',
		'quickswap',
		'sushiswap',
	],
}
